server:
  port: 8081
spring:
  profiles:
    active: redis,mybatisplus
  application:
    name: springboot
  web:
    resources:
      cache:
        period: 600
  mvc:
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
  #jackson 格式化时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #thymeleaf配置
  thymeleaf:
    cache: false #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix: .html
  messages:
    basename: i18n.login
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    namespace: 4c677c0f-234d-4472-a808-d861550efa8d
    register:
      group-name: dev
  # ============== nacos-config  ============== #
  config:
    server-addr: localhost:8848
    type: yaml
    namespace: 4c677c0f-234d-4472-a808-d861550efa8d
    auto-refresh: true
    group: dev
    data-id: springboot.yaml
    bootstrap:
      enable: true
      log-enable: true
