############################## mybatis-plus配置 开始  ##############################
mybatis-plus:
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
  type-aliases-package: pers.zitianqiong.mapper
  #MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法(XML 中有自定义实现)，需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  #TypeHandler 扫描路径，如果配置了该属性，SqlSessionFactoryBean 会把该包下面的类注册为对应的 TypeHandler
  type-handlers-package: pers.zitianqiong.handler
  global-config:
    banner: true
    #是否初始化 SqlRunner， SqlRunner为SQL增强工具，用于在代码中使用原生SQL
    enable-sql-runner: true
    db-config:
      # 主键类型  auto: 数据库ID自增， none:该类型为未设置主键类型(注解里等于跟随全局,全局里约等于 INPUT)，
      # input:用户输入ID(该类型可以通过自己注册自动填充插件进行填充)，assign-id: 分配ID (主键类型为number或string,雪花算法)，
      # assign-uuid: 分配UUID (主键类型为 string,UUID.replace("-",""))
      id-type: ASSIGN_ID
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认 0、表示未删除）
      logic-not-delete-value: 0
  configuration:
    # 配置的缓存的全局开关
    cache-enabled: true
    map-underscore-to-camel-case: false
    # 延时加载的开关
    lazyLoadingEnabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multipleResultSetsEnabled: true
    #Oracle数据库开启，否则使用updateAllColumnById()这种方法，如果列值为空，就会报错
    #jdbc-type-for-null: 'null'

############################## mybatis-plus配置 结束  ##############################
