spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:p6spy:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/springboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    #hikari数据库连接池
    hikari:
      pool-name: common-pool
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      maximum-pool-size: 30 #连接池最大连接数，默认是10
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1 from dual
  cache:
    type: redis
    redis:
      time-to-live: 60000
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    client-type: jedis
    jedis:
      pool:
        max-active: 10
    # 连接超时时间（毫秒）
    timeout: 5000
mybatis-plus:
  configuration:
    #日志输出在控制台,打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springfox:
  documentation:
    swagger-ui:
      enabled: true
