server:
  port: 8081
spring:
  profiles:
    active: dev,mybatisPlus
  application:
    name: springboot
  web:
    resources:
      cache:
        period: 600
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true
  #thymeleaf配置
  thymeleaf:
    cache: false #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    suffix: .html
  messages:
    basename: i18n.login
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  banner:
    location: classpath:banner.txt
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: springboot-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer
# ===== 自定义swagger配置 ===== #
swagger:
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3
  try-host: http://localhost:${server.port}
